### ISSUE TITLE
Remove Remote Resources

### ISSUE THREAD

**Issue by SteffTek** [Spellic-Dev/Public#4]
Remove Remote Resources (e.g. Google Fonts and other third parties) from the Source Code. GDPR Compliance

**Comment by ryzetech** [comment]
Noted for further inspection

**Comment by SteffTek** [comment]
**Bump**

**Comment by ryzetech** [comment]
thx4bump, am working on it

**Comment by ryzetech** [comment]
Okay I ran into a problem:
For some reason, I can import the font into BSS as a file but can't remove the import line in the HTML as it's forced. I think we could check for a change with some action at upload and remove the line via that as I'm too lazy to do it myself every time.

**Comment by ryzetech** [comment]
![grafik](https://user-images.githubusercontent.com/51242305/197336393-22809913-43f5-4ce2-86e7-0f8a6a10a6cd.png)
lol

**Comment by ryzetech** [comment]
should be fixed in #5 <3
